version: '3'
services:

  go:
    build:
      context: ..
      dockerfile: docker/go/Dockerfile
    container_name: ${GO_CONTAINER_NAME}
    env_file: .env
    ports:
      - "8090:8080"
    volumes:
      - ../app/:/app
    tty: true
    stdin_open: true
    networks:
      - go-net

  mongo:
    image: mongo:latest
    container_name: ${MONGO_CONTAINER_NAME}
    restart: always
    volumes:
      - "${MONGO_EXTERNAL_DATA}:/var/lib/mongodb/"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - go-net

  mongo-express:
    image: mongo-express:latest
    container_name: ${MONGO_EXPRESS_CONTAINER_NAME}
    restart: always
    depends_on:
      - mongo
    ports:
      - "8085:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
    networks:
      - go-net

networks:
  go-net:
    name: "go-net"
    driver: bridge