version: '3'
services:
  go:
    build:
      context: go
    container_name: ${GO_CONTAINER_NAME}
    env_file: .env
#    depends_on:
#      - db
    volumes:
      - "../backend/:/var/www/html/"
      - "${SSH_EXTERNAL_KEYS}:/home/user/.ssh"
    tty: true
    stdin_open: true
    networks:
      - go-net


#  mongo:
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
#
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: my_password
#      ME_CONFIG_MONGODB_URL: mongodb://admin:my_password@mongo:27017/" >> /tmp/mongodb/dd.yml

networks:
  go-net:
    driver: bridge
    external: true