root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
exclude_dir = ["vendor", "tmp", "docs"]
include_ext = ["go", "tpl", "tmpl", "html"]
delay = 1000 # ms

[log]
time = true